{{if .Values.global.blue.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-blue
  labels:
    tier: worker
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: worker
  template:
    metadata:
      labels:
        tier: worker
        slot: blue
    spec:
      containers:
      - image: {{.Values.image}}
        name: worker
{{end}}
